[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
engine = "DhKVzFTjzax7MeLEqiEXmEhm6ERSjehYaamqai5oPKZ7"

[programs.localnet]
engine = "DhKVzFTjzax7MeLEqiEXmEhm6ERSjehYaamqai5oPKZ7"
income-dispatcher = "5RBTApVVa2JYk2w5WhjxXPseWb4uCDMnBbtGCSVf4b2p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
create-clmm-pool = "ts-node scripts/create-clmm-pool.ts"
deposit = "ts-node scripts/deposit.ts"
init-launch = "ts-node scripts/init-launch.ts"
init-roster = "ts-node scripts/init-roster.ts"
litesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/litesvm.ts"
litesvm-basic = "yarn run test:litesvm:basic"
litesvm-full = "yarn run test:litesvm:full"
litesvm-raydium = "yarn run test:litesvm:raydium"
litesvm-dispatcher = "yarn run test:litesvm:dispatcher"
