[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
engine = "5W13VU4NkJbNHEX1CNFfjCzKGA7WeKqLzQoUDoLsoKjH"

[programs.devnet]
engine = "5W13VU4NkJbNHEX1CNFfjCzKGA7WeKqLzQoUDoLsoKjH"

# [programs.remote]
# engine = "HMVJWXWhpxEWWGhvLHYnTvkmYJcA819jAxw3EgdNYiYb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
litesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/litesvm.ts"
farm-sol = "ts-node scripts/farm-sol.ts"
sync-id = "node scripts/sync-program-id.js"
init-launch = "ts-node scripts/init-launch.ts"
init-launch-litesvm = "ts-node scripts/init-launch-litesvm.ts"
init-roster = "ts-node scripts/init-roster.ts"
deposit = "ts-node scripts/deposit.ts"
create-clmm-pool = "ts-node scripts/create-clmm-pool.ts"
debug-amm-config = "ts-node scripts/debug-amm-config.ts"
list-amm-configs = "ts-node scripts/list-amm-configs.ts"
check-idl = "ts-node scripts/check-idl.ts"
