[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
engine = "DhKVzFTjzax7MeLEqiEXmEhm6ERSjehYaamqai5oPKZ7"
income_dispatcher = "DPwfwgErHSmKLjGkadA4EL1zcCKU1ZhdaMUyUzJtTqCN"

[programs.devnet]
engine = "DhKVzFTjzax7MeLEqiEXmEhm6ERSjehYaamqai5oPKZ7"
income_dispatcher = "DPwfwgErHSmKLjGkadA4EL1zcCKU1ZhdaMUyUzJtTqCN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"

[[test.genesis]]
address = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"
program = "tmp/raydium_clmm.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tmp/mpl_token_metadata.so"

[[test.validator.account]]
address = "9iFER3bpjf1PTTCQCfTRu17EJgvsxo9pVyA9QWwEuX4x"
filename = "tmp/amm_config.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/raydium-clmm-anchor.test.ts'"
litesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/litesvm.ts"
litesvm-basic = "yarn run test:litesvm:basic"
litesvm-raydium = "yarn run test:litesvm:raydium"
litesvm-full = "yarn run test:litesvm:full"
pre-deploy-setup = "ts-node scripts/pre-deploy-setup.ts"
init-engine-config = "ts-node scripts/init-engine-config.ts"
init-launch = "ts-node scripts/init-launch.ts"
init-launch-preset = "ts-node scripts/init-launch-preset.ts"
init-launch-from-preset = "ts-node scripts/init-launch-from-preset.ts"
init-roster = "ts-node scripts/init-roster.ts"
init-roster-shard = "ts-node scripts/init-roster-shard.ts"
deposit = "ts-node scripts/deposit.ts"
finalize-roster-shard = "ts-node scripts/finalize-roster-shard.ts"
set-seed = "ts-node scripts/set-seed.ts"
prepare-pool-creation = "ts-node scripts/prepare-pool-creation.ts"
create-clmm-pool = "ts-node scripts/create-clmm-pool.ts"
add-clmm-liquidity = "ts-node scripts/add-clmm-liquidity.ts"
build-test = "anchor build -- --features test"
mint-spl = "ts-node scripts/mint-spl.ts"
